apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: logins.oauth2.example.com
spec:
  group: oauth2.example.com
  names:
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Login
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: logins
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - lg
    # singular name to be used as an alias on the CLI and for display
    singular: login
  scope: Namespaced
  # list of versions supported by this CustomResourceDefinition
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              expireSeconds:
                type: integer
              providerURL:
                type: string
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
